name: CI/CD to Google Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Debug the SERVICE_ACCOUNT_KEY
      - name: Debug ENV Vars
        run: |
          echo "Checking if SERVICE_ACCOUNT_KEY is set"
          echo PORT=${{ secrets.PORT }}
          echo DB_HOST=${{ secrets.DB_HOST }}
          echo DB_NAME=${{ secrets.DB_NAME }}
          echo DB_PASSWORD=${{ secrets.DB_PASS }}
          echo DB_USER=${{ secrets.DB_USER }}
          echo ML_URL=${{ secrets.ML_URL }}

      - name: Test Service Account
        run: |
          echo "SERVICE ACCOUNT is set: ${{ secrets.SERVICE_ACCOUNT_KEY }}"
